docs_dir: docs/book
site_dir: docs/html
extra:
  project: Components
  current_version: v3
  versions:
    - v3
    - v2
nav:
    - Home: index.md
    - v3:
      - "Quick Start": v3/quick-start.md
      - "Filters": v3/filter.md
      - "Strategies":
        - Introduction: v3/strategy.md
        - Collection: v3/strategies/collection.md
        - DateTimeImmutableFormatter: v3/strategies/datetime-immutable-formatter-strategy.md
        - Hydrator: v3/strategies/hydrator.md
        - Serializable: v3/strategies/serializable.md
      - "Aggregates": v3/aggregate.md
      - "Naming Strategies":
        - "Introduction": v3/naming-strategy/intro.md
        - "Identity": v3/naming-strategy/identity-naming-strategy.md
        - "Mapping": v3/naming-strategy/map-naming-strategy.md
        - "Underscore Mapping": v3/naming-strategy/underscore-naming-strategy.md
        - "Composite": v3/naming-strategy/composite-naming-strategy.md
      - "Plugin Managers": v3/plugin-managers.md
      - Migration: v3/migration.md
    - v2:
        - "Quick Start": v2/quick-start.md
        - Reference:
          - "Filters": v2/filter.md
          - "Strategies": v2/strategy.md
          - "Aggregates": v2/aggregate.md
          - "Naming Strategies":
            - "Identity": v2/naming-strategy/identity-naming-strategy.md
            - "Mapping": v2/naming-strategy/map-naming-strategy.md
            - "Underscore Mapping": v2/naming-strategy/underscore-naming-strategy.md
            - "Composite": v2/naming-strategy/composite-naming-strategy.md
    - "_hidden-legacy-page-links":
        - "_quick_start": quick-start.md
        - "_filters": filter.md
        - "_strategies": strategy.md
        - "_aggregates": aggregate.md
        - "_naming_strategies-identity": naming-strategy/identity-naming-strategy.md
        - "_naming_strategies-mapping": naming-strategy/map-naming-strategy.md
        - "_naming_strategies-underscore_mapping": naming-strategy/underscore-naming-strategy.md
        - "_naming_strategies-composite": naming-strategy/composite-naming-strategy.md
site_name: laminas-hydrator
site_description: "laminas-hydrator provides functionality for hydrating objects and extracting data from them. The component contains concrete implementations for a number of common use cases and provides interfaces for creating custom implementations."
repo_url: 'https://github.com/laminas/laminas-hydrator'
